### ISSUE TITLE
[Request] Make the documentation more obvious

### ISSUE THREAD

**Issue by faeldray** [D0CTOR-ZED/FloorMats#5]
I'm someone who actually tends to look stuff up but it took me way too long to find out that there was a command, and even longer to find out how to "open" mats.

I'm not sure the best way to do this but it could be something as simple as adding a tooltip to all the mats that says "See /floormats for more info". I think also the Info page in JEI is a great place to include the info you have in the /floormats command, but I can understand that you may not want to duplicate it.

Also including the documentation somewhere on how to "open" mats would be wonderful!

**Comment by D0CTOR-ZED** [comment]
Thank you for the feedback.  I like the idea of adding a JEI page and will try to do that in a future update.  I also see I need to update the wiki (https://github.com/D0CTOR-ZED/FloorMats/wiki; linked to from the curseforge page).  I tried to detail everything someone might need to know there (but that doesn't help if I don't update it).  I definitely need to address how the connections are changed since I went from a two-click system to just a single click aimed where the two mats meet.  I'll leave this issue open until I can address these issues.  Thanks again.

**Comment by faeldray** [comment]
Thanks for considering doing this, those sound like great ideas! And I know how easy it is to let documentation get away from you and become outdated. It's certainly something I've been guilty of myself.

I also realized that I wrote in my original comment "adding a _tool_" when I meant to say "adding a _tooltip_". That's what I get for making tickets at 3am. >.< I'll get that fixed.

**Comment by VallenFrostweaver** [comment]
I second this. I found the command only through this report and I still don't know what I need to do to allow all players to use the Floor Mats that I placed down as all I get is a click when I use a stick. I don't know what that means. I would have liked any player access by default and locking out others as a setting to change it to but that's just my personal preference. Thanks for the cool mod!

**Comment by D0CTOR-ZED** [comment]
@VallenFrostweaver , thanks for the feedback and I just wanted to let you know how to open a gilded floor mat so that they stop being specific to the players that placed them.  Currently, this info is only found in the changelog, as I haven't kept the documentation up to date, apologies for that.  It seems that the opening of the floor mat is done by holding an iron block in one hand while wrenching the floor mat with a connector (stick) held in the other hand.  It was an undocumented feature that was added when I added the camouflage floor mats, since they make more sense to be open to all players (which I believe they are by default).

**Comment by VallenFrostweaver** [comment]
Thank you for the info! Are you saying camo floor mats are open to all players on placement by default? If so, I can state that it's not. It's open to only me. If not, I'm guessing you are changing plans?

**Comment by faeldray** [comment]
I'm using some camo floor mats currently and can confirm that as well that by default, they only activate for the player who placed them. I was able to "open" them to all players by using the iron block/stick method.

**Comment by D0CTOR-ZED** [comment]
Oops.  I was actually just testing this as I worked on the documentation.  Seems like they should be open by default, so I'll see if I can work that into the next update.  Sorry for the misinformation.  I thought they started open.  Thank you both for the feedback.  It's nice to know someone is using my floor mats.

Edit: I forgot that the lists can be inverted, connector (stick) with a redstone torch in the off-hand so that the mat is only activated by players that didn't place it.  I'm not sure now what the default behavior for the camouflage floor mats should be.  Whatever it ends up being, I'll get the necessary info into the tool tip/commands/wiki.

**Comment by faeldray** [comment]
IMHO camo floor mats should work just like gilded floor mats since they really just do the same thing but look different. I feel like having them all default to being open to all players makes the most sense since most players on a server are usually fine with people going through their doors. And then the wrenches and such could be used to modify them if the player wanted more specific access.

**Comment by D0CTOR-ZED** [comment]
I've updated the wiki and just released an update that updates the commands and adds an expanding tool tip to the items.

I didn't change the default behavior of the camouflage floor mats since I realized that what makes sense depends on the use case, so consistency with gilded makes sense.  The expanding tool tip on them hopefully points players toward the info they need.

I didn't add a jei info page, and may still consider that, but I feel this update should help players find the info they need, so I'll close this request to make the documentation more obvious.  Thanks again to everyone for the feedback.  It's nice to know that people are actually using the mod.

**Comment by faeldray** [comment]
I finally had the chance to check out the updated tooltips/commands/wiki and the info is so much clearer now. Thank you so much for doing all of that!

I did notice one small thing, I think in the `/floormats modifiers` command, the header for the opener tools isn't localized properly. See the screenshot below.

![2021-09-03_03 15 29](https://user-images.githubusercontent.com/967709/131974341-1fc7664c-c89b-49ad-bbdd-c0ddc13e1cc1.png)
